name: Dump

on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ main ]

jobs:
  dump:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clone Dumpyara
         run: |
                  git clone https://github.com/cArN4gEisDeD/phoenix_firmware_dumper.git dumper

       - name: Setting up and Running Dumper
         run: |
              sudo chmod -R 777 dumper
              cd dumper
              sudo pip3 install wheel setuptools
              sudo bash setup.sh
              touch .tg_token
              echo "${{ secrets.BOT }}" >> ".tg_token"
              touch .github_orgname
              echo "cArN4gE-Dumps" >> ".github_orgname"
              touch .github_token
              echo "${{ secrets.GHTOKEN }}" >> ".github_token"
              touch .tg_chat
              echo "@cArN4gEDumps" >> ".tg_chat"
              git config --global user.email "carn4geisd3d@gmail.com"
              git config --global user.name "cArN4gEisDeD"
              git config user.email
              sudo bash dumper.sh $ROM_URL
env:
  ROM_URL: https://true-mirror-69.gitsauraj.workers.dev/0:/RMX1941_11_A.10-HardbrickFix.zip
