name: Dump

on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ main ]

jobs:
  dump:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clone Dumpyara
         run: |
              if [ -f "private.txt" ]
              then
                  git clone https://github.com/boxboi689/phoenix_firmware_dumper.git -b private dumper
              else
                  git clone https://github.com/boxboi689/phoenix_firmware_dumper.git dumper
              fi

       - name: Setting up and Running Dumper
         run: |
              sudo chmod -R 777 dumper
              cd dumper
              sudo pip3 install wheel setuptools
              sudo bash setup.sh
              touch .tg_token
              echo "${{ secrets.BOT }}" >> ".tg_token"
              touch .github_orgname
              echo "boxaltdumps" >> ".github_orgname"
              touch .github_token
              echo "${{ secrets.GHTOKEN }}" >> ".github_token"
              touch .tg_chat
              echo "@boxdumps" >> ".tg_chat"
              git config --global user.email "evanpherrao@gmail.com"
              git config --global user.name "boxboi689"
              git config user.email
              sudo bash dumper.sh $ROM_URL
env:
  ROM_URL: https://prukamger.prukamger.workers.dev/0:/miui_MERLIN_V12.5.2.0.RJOCNXM_dc5c5badb0_11.0.zip
